Added yml file generation and verifier class replacing random
bgsu-pal/paclab-transformer pull request #12
Opened 2024-11-26 17:53 UTC by rubalgoyal

2024-12-02 03:25 UTC, charles-moloney commented
Can we delete the files that this is adding that are not part of the business logic changed? Surely we don't need to merge 18,000 file changes to develop

2024-12-02 15:14 UTC, jckreg commented on benchmarks/Jarcionek/MTG-Deck-Builder/MTG-Deck-Builder-master/src/main/java/mtgdeckbuilder/frontend/CardsDisplayPanel.java
> -package mtgdeckbuilder.frontend;
In the last PR we removed the database, suitablePrgrms and benchmardks from the repo. These deletes seem like a duplicate. Is there any way to resolve these locally as they are lagging out the github difff page?

2024-12-04 23:24 UTC, rubalgoyal commented
I tried to remove unnecessary files and resolved the conflicts. Please let me know if any other change that needs to be done (I am new to git so learning things).

2024-12-05 17:25 UTC, charles-moloney commented
> I tried to remove unnecessary files and resolved the conflicts. Please let me know if any other change that needs to be done (I am new to git so learning things).

No worries! :) It is still saying there are 5000+ files being changed. We have recently configured the .gitignore to ignore files in database, benchmarks, and suitableprgms, but I think this isn't being reflected in your changes because they have already been committed. Our most current version of develop has these files deleted, which is what is creating the conflict. Could you please delete the following directories and commit that change?

/database/
/benchmarks/
/suitablePrgms/

2024-12-08 21:36 UTC, rubalgoyal commented
Hi @charles-moloney I took another shot and removed these directories from my last commit using following commands

git rm -rf database/
git rm -rf benchmarks/
git rm -rf suitablePrgms/

Can you check and confirm that these unnecessary files have been removed? Thanks.

2024-12-09 01:21 UTC, charles-moloney requested changes
Will advise being careful while merging (especially in transform/Main), but this overall looks good. Thank you for removing the extra files,

2024-12-09 01:21 UTC, charles-moloney commented on src/java/transform/Main.java
> +>>>>>>> ed176acbf9e3813d120e1e688579b6fc99ca5542:src/java/transform/Main.java
This seems like a leftover merge conflict marker

2024-12-09 18:36 UTC, jckreg requested changes
Charles marked one and I marked 2 other spots with merge conflict markers left over

2024-12-09 18:36 UTC, jckreg commented on .project
> +<<<<<<< HEAD
There are a couple of other spots that seem to have merge conflict markers left over

2024-12-09 18:36 UTC, jckreg commented on src/java/transform/visitors/TransformVisitor.java
> +<<<<<<< HEAD:src/java/transform/visitors/TransformVisitor.java
Merge conflict markers, looks like 2 separate instances of HEAD but essentially the same change

2024-12-09 18:40 UTC, jckreg commented on .idea/.gitignore
> +# Default ignored files
I believe the .idea files are from intelliJ or another IDE and shouldn't be included, there is a change in the other PR for adding these to the .gitignore

2024-12-09 18:43 UTC, jckreg commented on src/java/transform/Main.java
> +		//TODO: Temporary added some extra Print statements
Are these still temporary print statements? I like having them in personally on the runs that I have done. If they are temporary should they be removed or should we just remove the TODO and keep the print statements? Any thoughts?

2024-12-10 19:18 UTC, jckreg commented on svcomp-benchmarks/.DS_Store
We had recently added .DS_Store files to the .gitignore. Are these files needed?

2024-12-10 22:02 UTC, rubalgoyal commented on src/java/transform/Main.java
> +		//TODO: Temporary added some extra Print statements
I removed the //TODO comment.

2024-12-10 22:06 UTC, rubalgoyal commented
Hi @charles-moloney  and @jckreg thanks for the review and feedback. I have incorporated the changes suggested. Please let me know if anything is remaining.

Further, I have included my manually converted benchmarks for the SVCOMP submission in the folder **svcomp-benchmarks**.

2024-12-10 22:55 UTC, jckreg reviewed
These files should be removed

2024-12-10 22:55 UTC, jckreg commented on svcomp-benchmarks/.DS_Store
Please remove this

2024-12-10 22:55 UTC, jckreg commented on svcomp-benchmarks/ArrayBasedCollectionTimer/.DS_Store
Please Remove this

2024-12-10 22:55 UTC, jckreg commented on svcomp-benchmarks/Base64/.DS_Store
please remove this

2024-12-10 22:55 UTC, jckreg commented on svcomp-benchmarks/.idea/codeStyles/Project.xml
If we could get rid of the .idea folder and its contents as well that would be great

2024-12-10 22:58 UTC, jckreg submitted a review, later dismissed

2024-12-12 18:39 UTC, charles-moloney approved these changes

2024-12-12 18:41 UTC, jckreg approved these changes

2024-12-12 18:42 UTC, merged